language: ruby
install:
  gem uninstall bundler
  gem install bundler --version '2.1.4'
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate
